# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/NVD_Dev',
                'doc_host': 'https://CarloOtano.github.io',
                'git_url': 'https://github.com/CarloOtano/NVD_Dev',
                'lib_path': 'NVD_Dev'},
  'syms': {'NVD_Dev.core': {'NVD_Dev.core.foo': ('core.html#foo', 'NVD_Dev/core.py')}}}
